module.exports = {
    INVALID_USER_ID: "Invalid User ID",
    OTP_GENERATION_FAILED: "Failed to generate OTP",
    INVALID_CREDENTIALS: "Invalid Credentials",
    PASSWORD_GENERATION_FAILED: "Failed to generate password",
    PASSWORD_HASHING_FAILED: "Failed to hash password",
    ACCESS_TOKEN_FAILED: "Failed to generate access token",
    REFRESH_TOKEN_FAILED: "Failed to generate refresh token",
    USER_LOGGED_IN: "User logged in successfully",
    USER_LOGGED_OUT: "User logged out successfully",
    USER_LOGIN_FAILED: "Failed to login user",
    USER_SESSION_CREATED: "User session created successfully",
    USER_SESSION_CREATION_FAILED: "Failed to create user session",
    USER_SESSION_UPDATE_FAILED: "Failed to update user session",
    USER_SESSION_NOT_EXISTS: "User session does not exist",
    USER_CREATED: "User created successfully",
    USER_EXISTS: "User already exists!",
    USER_CREATION_FAILED: "Failed to create user!",
    USER_DETAILS_FETCHED: "User details fetched successfully",
    USER_LISTS_FETCHED: "User lists fetched successfully",
    USER_NOT_FOUND: "User not found",
    USER_UPDATE_FAILED: "Failed to update user!",
    USER_UPDATED: "User updated successfully",
    USER_DELETED: "User deleted successfully",
    USER_DELETE_FAILED: "Failed to delete user!",
    STORE_EXISTS: "Store already exists for this number!",
    STORE_CREATED: "Store created successfully",
    STORE_FETCHED: "Store data fetched successfully",
    STORE_NOT_FOUND: "Store not found",
    STORE_NOT_EXIST_RADIUS: "No stores found within the specified radius",
    STORE_UPDATED: "Store updated successfully",
    STORE_UPDATE_FAILED: "Store update failed",
    STORE_DELETED: "Store deleted successfully",
    STORE_DELETE_FAILED: "Store deletion failed",
    STORE_CREATION_FAILED: "Failed to create store!",
    INVALID_STORE_ID: "Invalid store ID",
    OTP_GENERATED: "OTP generated successfully",
    INVALID_OTP: "Invalid OTP",
    OTP_EXPIRED: "OTP has expired",
    USER_ONBOARDING_STEP_UPDATE_SUCCESS: "User onboarding step - {step} updated successfully",
    USER_ONBOARDING_STEP_UPDATE_FAILED: "Failed to update user onboarding step - {step}",
    INVALID_ONBOARDING_STEP: "Invalid onboarding step",
    USER_ADDRESS_NOT_EXISTS: "User address details does not exist",
    ONBOARD_STEP_UPDATE_FAILED: "Failed to update onboarding step",
    ORDER_PLACEMENT_FAILED: "Failed to place order",
    ORDER_PLACED: "Order placed successfully",
    ORDER_NOT_FOUND: "Order not found",
    ORDER_FETCHED: "Order details fetched successfully",
    ORDER_UPDATE_FAILED: "Failed to update order",
    ORDER_UPDATED: "Order updated successfully",
    ORDER_ALREADY_TAKEN: "Order already taken by another store",
    INVALID_LOCATION: "Invalid location coordinates",
};